### ISSUE TITLE
New biblio references for inductive conductimeter + internship offer in Plouzané

### ISSUE THREAD

**Issue by epoirierIRD** [DIYOceanography/DIYOceanography_BZH#1]
Salut,
Je voudrai rajouter les références suivantes à la rubrique biblio capteur inductifs pour la conductivité.

https://www.sciencedirect.com/science/article/abs/pii/S0924424719315912
Kang Hui Song, Jang Hyon, Kim Gum Chol, Yu Song Chol, Kim Yong Hyok, A new design of inductive conductivity sensor for measuring electrolyte concentration in industrial field

https://ieeexplore.ieee.org/document/10268875
Rajeev Raghavan Ashokan, Gopalan Suresh, Rajamani Ramesh,
Naval Physical and Oceanographic Laboratory (NPOL), Kochi, India, Toroidal Seawater Conductivity Sensors and Instrumentation for Antisubmarine Warfare

C'est tiré d'une offre de stage de la société eOdyn pour un sujet nous intéressant. Collab à envisager avec l'entreprise? https://fr.indeed.com/viewjob?jk=570cbdd0d46d1d9f

**Comment by apatlpo** [comment]
@epoirierIRD, je viens de réaliser qu'on était sur GH pas sur la liste sympa, je transporte là-bas.

**Comment by apatlpo** [comment]
Merci Aurélien pour l'information et je suis partant pour rejoindre la
biblio partagée.
Je te présente également Lucas Charron (en copie), le développeur de la
bouée qui va s'occuper du développement du capteur de salinité.
A+
*Alexey*
